#!/bin/bash

set -e

if [ "$#" -ne 1 ]; then
    echo "You need to specify the size of the swap being created"
    echo "Usage: $0 1G"
    exit 1
fi

# Create the swap file
sudo fallocate -l $1 /swapfile
sudo chmod 600 /swapfile
sudo mkswap /swapfile

# Enable swap usage
sudo swapon /swapfile

# Make the swap permanent
echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab
