#!/bin/bash

PASSWORD_FILE=$(dirname `realpath $0`)/../.ssh/id_rsa
PASSWORD_FILE=$(realpath $PASSWORD_FILE)

FILES=$(dirname `realpath $0`)/../vnc-shared
FILES=$(realpath $FILES)

mkdir -p $FILES

if ! test -f "$PASSWORD_FILE"; then
    echo "Using $PASSWORD_FILE to create a password. Please ensure that it exists."
    exit 1
fi

PASSWORD=$(cat $PASSWORD_FILE | head -n 2 | tail -n 1 | /usr/bin/md5sum | cut -d ' ' -f 1)
docker run -it -p 127.0.0.1:5901:5901 -v $FILES:/files  -e VNC_RESOLUTION=1024x768 -e VNC_PW=$PASSWORD consol/centos-xfce-vnc
