#!/bin/bash

if [ -z "$1" ] || [ ! -f "$1" ]; then
  echo "Usage: $0 file.mov"
  exit
fi

docker run -it \
    -v `pwd`:/srv/screengif/input \
    --rm \
    ambroselli/screencast-gif \
    /bin/bash -c "umask 002 && bin/screengif -i 'input/$1' -o 'input/$1.gif'"
