#!/bin/bash
set -e

read -s -p "Encryption key: " KEY

decrypt_file() {
  INPUT=$1
  EMPTY=""
  openssl enc -aes-256-cbc -d -in "$INPUT" -out ${INPUT/.enc/$EMPTY} -pass "pass:$2"
}


decrypt_file /home/carl/.aws/credentials.enc $KEY
decrypt_file /home/carl/.ssh/id_rsa.enc $KEY
decrypt_file /home/carl/.config/rclone/rclone.conf.enc $KEY

chmod 600 /home/carl/.ssh/id_rsa

echo "Successfully unsealed"

