#!/bin/bash

NOTES_LOCATOR=$HOME/.notes-dir
if ! test -f "$NOTES_LOCATOR"; then
  echo "Please create file at $NOTES_LOCATOR with folder of notes first"
  exit 1
fi

clear  
echo " "
cat $(cat $NOTES_LOCATOR)/todo* | sed -n '/# Work/,$p' | tail -n +2 | awk 'NF' | sort
echo " "
